language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27-111
  - python: 3.6
    env: TOXENV=py36-111
  - python: 3.6
    env: TOXENV=py36-21
  - python: 2.7
    env: TOXENV=docs
  - python: 2.7
    env: TOXENV=flake8
before_install:
- sudo apt-get -q -y update
- sudo apt-get remove -q -y binutils gdal-bin libproj-dev libgeos-c1v5
- sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get -q -y install build-essential
- sudo apt-get -q -y install binutils gdal-bin libproj-dev libgeos-c1v5
install:
- pip install pip wheel
- pip install tox
script:
- tox -e $TOXENV
notifications:
  irc:
    channels:
    - irc.freenode.org#django-floppyforms
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  user: gremu
  password:
    secure: HAgxb7ebUfIQSfcxtjKoXO3FCBiujCo4GU2lYO8IUPeSdurPG6e+uABzwg88d7Zt1Zuay2eleAJzqhvwU2bCOKr68wjkNw3yWRslvLAMK3vj2LPPoWYsgmLJ1YiOvPloCdD2sIVSmpLEiN5HLUteh5j6D2BUbw67a9S2TXx1J8c=
  on:
    tags: true
    repo: jazzband/django-floppyforms
    condition: "$TOXENV = py36-21"
